### ISSUE TITLE
/History issue

### ISSUE THREAD

**Issue by itsWarHammer** [OopsieWoopsie/BanAnnouncer#12]
if i check the history of a player it sends an unmute embed to discord {AdvancedBans}

**Comment by itsWarHammer** [comment]
also when a player's mute time is done it sends an un-mute embed to discord

**Comment by OopsieWoopsie** [comment]
> if i check the history of a player it sends an unmute embed to discord {AdvancedBans}

Hello, that's an issue with [AdvancedBan](https://github.com/DevLeoko/AdvancedBan), BanAnnouncer will only send a message when the Punishment plugin tells to do it.

> also when a player's mute time is done it sends an un-mute embed to discord

When a temporary punishment is made, the un-punish event will be sent when it ends, and again, BanAnnouncer will be notified to send that message. I don't really think this second one is a bug or something due that is an intended function.

**Comment by itsWarHammer** [comment]
alright but as for the second issue that only happens with mutes but when i temporarily ban someone and the its time has passed it wont send any message

**Comment by OopsieWoopsie** [comment]
I took a look at AdvancedBan's code and found that when you do /history, the punishments are check to find if some has expired and in case it is, the RevokePunishmentEvent is called, therefore BanAnnouncer sends the message.

Question to get out some doubts:
Were both messages the same (taking in count that you only muted the user one time)? like if it got sended two times

**Comment by itsWarHammer** [comment]
yeah one time it sent the same message 3 times

**Comment by OopsieWoopsie** [comment]
Can you test muting a random player one time for 10 seconds? then wait to get the unmute message and run /history to check if the message gets send again

**Comment by itsWarHammer** [comment]
this time it didnt send an embed for un-mute when the time finished but it did when i did /history

**Comment by OopsieWoopsie** [comment]
Thank you! That will be useful ^^

**Comment by itsWarHammer** [comment]
https://pastebin.com/EZ76N4iB just spotted this error on startup

**Comment by OopsieWoopsie** [comment]
Don't worry, those are just warnings and the involved libs are stable!

**Comment by itsWarHammer** [comment]
alright thanks

**Comment by OopsieWoopsie** [comment]
Fixed here https://github.com/OopsieWoopsie/AutoRevoker
