### ISSUE TITLE
Cyrillic letters are not displayed.

### ISSUE THREAD

**Issue by bloodyearth** [OopsieWoopsie/BanAnnouncer#2]
Hi. I try translate announcements from this plugin to russian language, but cyrillic letters displayed like "??????". How to fix it?

https://ibb.co/3FSyCP3

**Comment by OopsieWoopsie** [comment]
Hi, please send me your .json file containing your text (embed message), so I can use it for make the tests.

**Comment by bloodyearth** [comment]
> Hi, please send me your .json file containing your text (embed message), so I can use it for make the tests.


[ban.zip](https://github.com/OopsieWoopsie/BanAnnouncer/files/3498712/ban.zip)

**Comment by OopsieWoopsie** [comment]
Thank you, I will look at it and I will try to figure out what happens ^^

**Comment by OopsieWoopsie** [comment]
I just opened it, the file literally says "?????". xD
Probably your text editor is not saving the characters.

**Comment by bloodyearth** [comment]
Wait... Seems like it's saves in incorrect format.

**Comment by bloodyearth** [comment]
Maybe problem in my text editor. I make some tests and reply you.

**Comment by bloodyearth** [comment]
All unsuccessful. I trying edit it with Notepad++, but now i'm getting messages like "µŃ€ĐĽĐ°Đ˝ĐµĐ˝Ń‚Đ" https://ibb.co/4F2C2g1

[ban.zip](https://github.com/OopsieWoopsie/BanAnnouncer/files/3498799/ban.zip)

**Comment by OopsieWoopsie** [comment]
Hello, I have just tried your file and it seems to work on my end.
After doing some tests, I have suspected that Charset.defaultCharset() is returning ISO-8859-1 for you. I will update the plugin to avoid using that method and use UTF-8 instead.

**Comment by OopsieWoopsie** [comment]
The code I used:

```java
String text = "получил перманентный бан";

byte[] iso8859 = text.getBytes("ISO-8859-1");
System.out.println(new String(iso8859));
// output: ??????? ???????????? ???

byte[] utf8 = text.getBytes("UTF-8");
System.out.println(new String(utf8));
// output: получил перманентный бан
```

**Comment by OopsieWoopsie** [comment]
It should be fixed now, please update Spicord and tell me if it works ^^

**Comment by bloodyearth** [comment]
> It should be fixed now, please update Spicord and tell me if it works ^^

Now it works perfect. Thank you very much. :)
