### ISSUE TITLE
Announcement on punshiment expiration with AdvancedBan

### ISSUE THREAD

**Issue by wanou067** [OopsieWoopsie/BanAnnouncer#20]
Hi,
Actually with advanced bans, when you tempban, tempwarn or tempmute someone, the message appears. Then if you decide to unmute this person, it will broadcast a message for example "Wanou067 unbanned player". But if i don't unban the user and let the timer finish, it will also broadcast the unban message, it would be great if we have a "manual unban message" or somethings else to set differents messages.

**Comment by OopsieWoopsie** [comment]
Added the "Automatic" suffix to messages of expired punishments
