### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by squeaky2137** [OopsieWoopsie/BanAnnouncer#22]
Hello, 
I have 3 suggestions.
1. Make an option / way you can add the date the punishment was made in the footer if isnt already possible.
2. Have a link to color codes on spigot ( optional )
3. This one is just to make format better but make the preset format for temp punishments be normal but put the duration on a new line under ,so for mute it would be...

The player ‘%player%’ was temporarily muted by ‘%staff%’ for ‘%reason%’.
Duration: ‘%duration%’

**Comment by OopsieWoopsie** [comment]
1. Use 0000-00-00T00:00:00 in the footer time, it will be replaced with the current time
2. You can't use colors on Discord
3. Use \n to create a new line

**Comment by squeaky2137** [comment]
Thank you and sorry by colors i meant the embed colors

**Comment by OopsieWoopsie** [comment]
You can use this site to create and visualize your Embed messages, this also has a Color Picker which you can use to change the colors https://leovoel.github.io/embed-visualizer/
