### ISSUE TITLE
Cannot find addon.

### ISSUE THREAD

**Issue by Foxiar** [OopsieWoopsie/BanAnnouncer#23]
Hello, i made everything in your tutorial, but plugin tells me:

[WARNING] [Spicord] The addon with the id 'ban_announcer' was not found.

my config of spicord:
https://pastebin.com/AMXQ0BLX

**Comment by OopsieWoopsie** [comment]
Hi, can you send me your server log?

**Comment by Foxiar** [comment]
I forgot tell you that i run bungeecord. 
https://pastebin.com/xGazwqnK
this is what writes bungeecord when i start server

**Comment by OopsieWoopsie** [comment]
You don't even have BanAnnouncer nor a punsihment plugin in your plugins folder...

**Comment by Foxiar** [comment]
yes! it work. Thank you. I was putting it into addons folder :D
