### ISSUE TITLE
The addon with the id 'ban_announcer' was not found.

### ISSUE THREAD

**Issue by Kike-2006** [OopsieWoopsie/BanAnnouncer#27]
Hello.
I have a problem, when I start my 1.16.4 server, spicord throws me an error in the console.

I need help!

[03:46:16] [ForkJoinPool.commonPool-worker-0/WARN]: [Spicord] The addon with the id 'ban_announcer' was not found.

**Comment by OopsieWoopsie** [comment]
Hi, can you send me your server log? The part when the server starts loading until that message appears

**Comment by Kike-2006** [comment]
Sure!


https://pastebin.com/wZkijeW1

**Comment by OopsieWoopsie** [comment]
BanAnnouncer didnt't loaded because you have an invalid json file. I don't know which one but is an embed message in the "BanAnnouncer/embed" folder.

You can use this site https://leovoel.github.io/embed-visualizer/ to validate your embed files.
