### ISSUE TITLE
BanAnnouncer does not work if MySQL is enabled in LiteBans.

### ISSUE THREAD

**Issue by bloodyearth** [OopsieWoopsie/BanAnnouncer#3]
I used BanAnnouncer for a while and everything was fine. But today I connected LiteBans to MySQL and BanAnnouncer stopped working.
If return the driver back to H2 in LiteBans, BanAnnouncer starts working again.

Is it possible to fix this? I need to use MySQL. :)

**Comment by OopsieWoopsie** [comment]
Hi, I haven't tested it yet but there shouldn't be a problem due that BanAnnouncer uses the LiteBans API, the only SQL sentence on this plugin is the one at [this line](https://github.com/OopsieWoopsie/BanAnnouncer/blob/master/src/eu/mcdb/ban_announcer/listener/LiteBans.java#L30).
Are you getting some exception or warning in the console?

**Comment by bloodyearth** [comment]
I do not see any critical errors about this.

Here is my server startup log. Spicord debugging is enabled if it is important.
https://hastebin.app/5d8b3a2a4798f8001c0daa7f

**Comment by OopsieWoopsie** [comment]
I have just tried using LiteBans (2.3.18 - same as yours) with MySQL and everything works perfectly, the log you sent is ok, can you provide the log when you ban or punish someone?

**Comment by bloodyearth** [comment]
Hmm... I test it on my local computer with local database and this work fine... 
Sorry for the false alarm. Maybe something is incorrectly configured on my dedicated server.
