### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by Ceddix** [OopsieWoopsie/BanAnnouncer#4]
Hay, when I start the server, the console says:
`The addon with the key 'ban_announce' was not found.`

And the plugin doesn't work! Why?
I use Paper 1.14, I have AdvancedBan and the config.yml is right! (I have  registered an channel!)

Pls help me!

**Comment by OopsieWoopsie** [comment]
"The addon with the key 'ban_announce' was not found" because the addon key is ban_announcer
With the R at the end :)

**Comment by Ceddix** [comment]
Thx!
