### ISSUE TITLE
I can not run.

### ISSUE THREAD

**Issue by TheAberto** [OopsieWoopsie/BanAnnouncer#8]
i did all what is neccesary on page.

My console told: `[SEVERE] [BanAnnouncer] The punishment manager 'LiteBans' is not compatible with BanAnnouncer, you can request the integration with it on https://github.com/OopsieWoopsie/BanAnnouncer/issues`

and i came here.

**Comment by OopsieWoopsie** [comment]
Write "LiteBans" in lowercase ;) like its on the config
