### ISSUE TITLE
Can add "reload" command in plugin?

### ISSUE THREAD

**Issue by haer0248** [OopsieWoopsie/BanAnnouncer#9]
Excuse me, can add reload command in plugin?
Because I does not restart the server often :(

**Comment by OopsieWoopsie** [comment]
Hello!
That's already on my to-do list, it will be eventually added ^^

**Comment by haer0248** [comment]
Thanks, I love this plugin <3!

**Comment by OopsieWoopsie** [comment]
Added the -bareload Discord command on the latest version
